In [4]:
import numpy as np
import pandas as pd

In [5]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
    
})

In [6]:
df.head()

,color
0,red
1,blue
2,green
3,green
4,red


In [7]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [8]:
lbl_encoder.fit_transform(df[['color']])

/opt/anaconda3/envs/campusx/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [9]:
lbl_encoder.transform([['red']])

/opt/anaconda3/envs/campusx/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [10]:
from sklearn.preprocessing import OrdinalEncoder


In [11]:
df=pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})
df

,size
0,small
1,medium
2,large
3,medium
4,small
5,large


In [ ]:
##instance of ordinal encoder
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [13]:
en=encoder.fit_transform(df[['size']])

In [17]:
import pandas as pd
df['size_new']=pd.DataFrame(en.astype(int))

In [18]:
df

,size,size_new
0,small,0
1,medium,1
2,large,2
3,medium,1
4,small,0
5,large,2


In [15]:
encoder.transform([['small']])

/opt/anaconda3/envs/campusx/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])