In [40]:
import numpy as np
import pandas as pd

In [41]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
    
})

In [42]:
df.head()

,color
0,red
1,blue
2,green
3,green
4,red


In [43]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [44]:
lbl_encoder.fit_transform(df[['color']])

/opt/anaconda3/envs/campusx/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [45]:
lbl_encoder.transform([['red']])

/opt/anaconda3/envs/campusx/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [46]:
from sklearn.preprocessing import OrdinalEncoder


In [47]:
df=pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})
df

,size
0,small
1,medium
2,large
3,medium
4,small
5,large


In [48]:
##instance of ordinal encoder
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [49]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [50]:
encoder.transform([['small']])

/opt/anaconda3/envs/campusx/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])