In [3]:


import numpy as np


In [11]:
##creating arrays using numpy
##1D array
arr1 = np.array([1, 2, 3, 4, 5])

print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


In [15]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
##creating 2d array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3.shape)

(2, 3)


In [18]:
arr4 = np.arange(0, 10, 2 )
print(arr4)
arr4.reshape(5, 1)


[0 2 4 6 8]


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
print(np.ones((3,4)))
print(np.zeros((2,6)))
print(np.eye(4))  # identity matrix

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
##attributes of numpy arrays
arr5 = np.array([[1,2,3], [4,5,6]])
print(arr5)
print(arr5.shape) ##dimensions
print(arr5.ndim) ##number of dimensions
print(arr5.dtype)##data type
print(arr5.size) ##number of elements
print(arr5.itemsize) ##size of each element in bytes

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64
6
8


In [ ]:
### numpy vectorized operations
array1= np.array([1, 2, 3, 4, 5])
array2= np.array([6, 7, 8, 9, 10])

print(array1 + array2) ##addition
print(array1 - array2) ##subtraction
print(array1 * array2) ##multiplication(elementwise)
print(array1/ array2) ##division(elementwise)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [ ]:
##universal functions in numpy
arr6 = np.array([2, 3, 4, 5, 6])
print(np.sqrt(arr6)) ##square root
print(np.exp(arr6))  ##exponential
print(np.log(arr6))  ##natural logarithm
print(np.sin(arr6))  ##sine
print(np.cos(arr6))  ##cosine
print(np.tan(arr6))  ##tangent

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]


In [38]:
##array indexing and slicing
arr = np.array([[1,2,3,4], [5, 6,7,8], [9,10,11,12]])
print(arr[1,2]) ##accessing element at 2nd row and 3rd column
print(arr[1:])
print(arr[1: , 2:])
print(arr[:2, 2:])

7
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [40]:
##modifying array elements
arr[0, 0] = 99

print(arr)
arr[1:] = 100
print(arr)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 99   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [43]:
### statistical concept: Normalization
##to change our data to have a mean of 0 and standard deviation of 1
data = np.array([10, 20, 30, 40, 50])
variance = np.var(data)
print("Variance:", variance)
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

Variance: 200.0
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [49]:
##logical operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5) ##masking
data[data > 5]##filtering
data[(data > 3) | (data < 8)] ##combining conditions

[False False False False False  True  True  True  True  True]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])